version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: delivery_mysql
    restart: always
    environment:
      MYSQL_DATABASE: delivery_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"