version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: delivery-mysql
    restart: always
    environment:
      MYSQL_DATABASE: delivery_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend
    container_name: delivery-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/delivery_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

  frontend:
    build: ./frontend
    container_name: delivery-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend